### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by drmcnelson** [JamesBremner/windex#5] opened 2024-01-30 01:45 UTC
g++ -g ../../demo/demo.cpp -o../../bin/demo.exe  -I../../include -I../../../../code_ext/boost/boost1_78 -lgdiplus -lgdi32 -lcomdlg32 -lComctl32
mingw32-make : In file included from ../../demo/demo.cpp:5:
At line:1 char:1
+ mingw32-make -f simple_demo_makefile.txt 2>&1 > compileerrors.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (In file include...emo/demo.cpp:5::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
../../include/propertygrid.h:4:10: fatal error: boost/property_tree/ptree.hpp: No such file or directory
    4 | #include <boost/property_tree/ptree.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
mingw32-make: *** [simple_demo_makefile.txt:9: demo] Error 1

**Comment by JamesBremner** [comment] 2024-01-30 14:23
Duplicate of #4

**Closed as completed by JamesBremner** 2024-01-30 14:23 UTC
Labels: duplicate
